[package]
name = "gh-config-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gh-config-cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] } # Added "env" feature
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
reqwest = { version = "0.11", features = ["json", "blocking"] }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
serde_json = "1.0"
thiserror = "1.0" # Added for error handling