name: Validate GitHub Org Config

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  validate-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build CLI
        run: cargo build --release
      - name: Validate Config (Dry Run)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          RUST_LOG: info
        run: ./target/release/gh-config-cli --config repos.yaml --token $GITHUB_TOKEN --dry-run

  apply-config:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: validate-config
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build CLI
        run: cargo build --release
      - name: Apply Config
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          RUST_LOG: info
        run: ./target/release/gh-config-cli --config repos.yaml --token $GITHUB_TOKEN